
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.8.2
 * Query Engine version: 2060c79ba17c6bb9f5823312b6f6b7f4a845738e
 */
Prisma.prismaVersion = {
  client: "6.8.2",
  engine: "2060c79ba17c6bb9f5823312b6f6b7f4a845738e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CurrencyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  symbol: 'symbol',
  type: 'type',
  precision: 'precision',
  isActive: 'isActive',
  isDefault: 'isDefault',
  contractAddress: 'contractAddress',
  blockchain: 'blockchain',
  withdrawalFeeFixed: 'withdrawalFeeFixed',
  withdrawalFeePercent: 'withdrawalFeePercent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  displayUsername: 'displayUsername',
  phone: 'phone',
  cashtag: 'cashtag',
  phoneVerified: 'phoneVerified',
  isVerified: 'isVerified',
  passwordHash: 'passwordHash',
  role: 'role',
  status: 'status',
  totalXp: 'totalXp',
  currentLevel: 'currentLevel',
  referralCode: 'referralCode',
  commissionRate: 'commissionRate',
  twoFactorEnabled: 'twoFactorEnabled',
  isOnline: 'isOnline',
  twoFactorSecret: 'twoFactorSecret',
  image: 'image',
  twoFactorRecoveryCodes: 'twoFactorRecoveryCodes',
  lastLogin: 'lastLogin',
  lastIp: 'lastIp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  activeWalletId: 'activeWalletId',
  referrerId: 'referrerId',
  firstName: 'firstName',
  lastName: 'lastName',
  avatarUrl: 'avatarUrl',
  dob: 'dob',
  gender: 'gender',
  preferredCurrencyId: 'preferredCurrencyId',
  timezone: 'timezone',
  locale: 'locale',
  mfaEnabled: 'mfaEnabled',
  mfaSecret: 'mfaSecret'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  username: 'username',
  name: 'name',
  activeGameId: 'activeGameId',
  ipAddress: 'ipAddress',
  startTime: 'startTime',
  endTime: 'endTime',
  lastActivityAt: 'lastActivityAt',
  userAgent: 'userAgent',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  refreshToken: 'refreshToken',
  active: 'active',
  token: 'token',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProfileScalarFieldEnum = {
  id: 'id',
  balance: 'balance',
  totalXpFromOperator: 'totalXpFromOperator',
  activeCurrencyType: 'activeCurrencyType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  currentGameSessionid: 'currentGameSessionid',
  userId: 'userId',
  otherUserid: 'otherUserid',
  role: 'role',
  operatorAccessId: 'operatorAccessId'
};

exports.Prisma.SettingsScalarFieldEnum = {
  id: 'id',
  theme: 'theme',
  language: 'language',
  emailNotifications: 'emailNotifications',
  smsNotifications: 'smsNotifications',
  pushNotifications: 'pushNotifications',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.WalletScalarFieldEnum = {
  id: 'id',
  balance: 'balance',
  isActive: 'isActive',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  currencyId: 'currencyId',
  bonusBalance: 'bonusBalance',
  lockedBalance: 'lockedBalance'
};

exports.Prisma.OperatorAccessScalarFieldEnum = {
  id: 'id',
  name: 'name',
  operator_secret: 'operator_secret',
  operator_access: 'operator_access',
  callback_url: 'callback_url',
  active: 'active',
  permissions: 'permissions',
  ips: 'ips',
  description: 'description',
  last_used_at: 'last_used_at',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ownerId: 'ownerId',
  acceptedPayments: 'acceptedPayments',
  ownedById: 'ownedById'
};

exports.Prisma.AchievementScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  xpReward: 'xpReward',
  iconUrl: 'iconUrl',
  secret: 'secret',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  blur: 'blur'
};

exports.Prisma.GameScalarFieldEnum = {
  id: 'id',
  name: 'name',
  title: 'title',
  goldsvetData: 'goldsvetData',
  description: 'description',
  provider: 'provider',
  category: 'category',
  tags: 'tags',
  isActive: 'isActive',
  thumbnailUrl: 'thumbnailUrl',
  bannerUrl: 'bannerUrl',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  featured: 'featured',
  operatorId: 'operatorId'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  published: 'published',
  tags: 'tags',
  viewCount: 'viewCount',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  authorId: 'authorId'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  postId: 'postId',
  authorId: 'authorId'
};

exports.Prisma.GameSpinScalarFieldEnum = {
  id: 'id',
  spinData: 'spinData',
  createdAt: 'createdAt',
  grossWinAmount: 'grossWinAmount',
  currencyId: 'currencyId',
  gameSessionId: 'gameSessionId',
  wagerAmount: 'wagerAmount',
  sessionId: 'sessionId',
  timeStamp: 'timeStamp'
};

exports.Prisma.GameSessionScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  sessionData: 'sessionData',
  sessionId: 'sessionId',
  currencyId: 'currencyId',
  startedAt: 'startedAt',
  endTime: 'endTime',
  startTime: 'startTime',
  ipAddress: 'ipAddress',
  startingBalance: 'startingBalance',
  userAgent: 'userAgent',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  totalWagered: 'totalWagered',
  totalWon: 'totalWon',
  userId: 'userId',
  gameId: 'gameId',
  profileId: 'profileId'
};

exports.Prisma.UserAchievementScalarFieldEnum = {
  id: 'id',
  unlockedAt: 'unlockedAt',
  metaData: 'metaData',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  achievementId: 'achievementId'
};

exports.Prisma.XpEventScalarFieldEnum = {
  id: 'id',
  points: 'points',
  source: 'source',
  sourceId: 'sourceId',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  isRead: 'isRead',
  readAt: 'readAt',
  actionUrl: 'actionUrl',
  imageUrl: 'imageUrl',
  metadata: 'metadata',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  channel: 'channel',
  content: 'content',
  mediaUrl: 'mediaUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  authorId: 'authorId'
};

exports.Prisma.FriendshipScalarFieldEnum = {
  id: 'id',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  requesterId: 'requesterId',
  receiverId: 'receiverId'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  originatorUserId: 'originatorUserId',
  receiverUserId: 'receiverUserId',
  walletId: 'walletId',
  type: 'type',
  status: 'status',
  amount: 'amount',
  netAmount: 'netAmount',
  feeAmount: 'feeAmount',
  productId: 'productId',
  currencyId: 'currencyId',
  balanceBefore: 'balanceBefore',
  balanceAfter: 'balanceAfter',
  bonusBalanceBefore: 'bonusBalanceBefore',
  bonusBalanceAfter: 'bonusBalanceAfter',
  bonusAmount: 'bonusAmount',
  wageringRequirement: 'wageringRequirement',
  wageringProgress: 'wageringProgress',
  description: 'description',
  provider: 'provider',
  providerTxId: 'providerTxId',
  relatedGameId: 'relatedGameId',
  relatedRoundId: 'relatedRoundId',
  metadata: 'metadata',
  processedAt: 'processedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GameLaunchLinkScalarFieldEnum = {
  id: 'id',
  token_internal: 'token_internal',
  currency: 'currency',
  player_operator_id: 'player_operator_id',
  mode: 'mode',
  meta: 'meta',
  request_ip: 'request_ip',
  user_agent: 'user_agent',
  session_url: 'session_url',
  state: 'state',
  active: 'active',
  expires_at: 'expires_at',
  extra_meta: 'extra_meta',
  token_original: 'token_original',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  gameId: 'gameId',
  operatorId: 'operatorId'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  url: 'url',
  iconUrl: 'iconUrl',
  productType: 'productType',
  bonusCode: 'bonusCode',
  bonusTotalInCredits: 'bonusTotalInCredits',
  isActive: 'isActive',
  currencyId: 'currencyId',
  priceInCents: 'priceInCents',
  amountToReceiveInCredits: 'amountToReceiveInCredits',
  bestValue: 'bestValue',
  discountInCents: 'discountInCents',
  bonusSpins: 'bonusSpins',
  isPromo: 'isPromo',
  totalDiscountInCents: 'totalDiscountInCents',
  shopId: 'shopId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  transactionId: 'transactionId'
};

exports.Prisma.EventLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  data: 'data',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  timestamp: 'timestamp',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  actorId: 'actorId'
};

exports.Prisma.OperatorInvitationScalarFieldEnum = {
  id: 'id',
  operatorId: 'operatorId',
  email: 'email',
  role: 'role',
  token: 'token',
  expiresAt: 'expiresAt',
  acceptedAt: 'acceptedAt',
  invitedById: 'invitedById'
};

exports.Prisma.VipInfoScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  level: 'level',
  currentLevelXp: 'currentLevelXp',
  totalXp: 'totalXp',
  nextLevelXpRequired: 'nextLevelXpRequired',
  cashbackPercentage: 'cashbackPercentage',
  prioritySupport: 'prioritySupport',
  specialBonusesAvailable: 'specialBonusesAvailable',
  dailyBonusClaimedAt: 'dailyBonusClaimedAt',
  weeklyBonusClaimedAt: 'weeklyBonusClaimedAt',
  monthlyBonusClaimedAt: 'monthlyBonusClaimedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserRewardScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  rewardType: 'rewardType',
  description: 'description',
  status: 'status',
  amount: 'amount',
  currencyId: 'currencyId',
  metaData: 'metaData',
  claimedAt: 'claimedAt',
  expiresAt: 'expiresAt',
  availableFrom: 'availableFrom',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  vipLevelRequirement: 'vipLevelRequirement'
};

exports.Prisma.VipTaskScalarFieldEnum = {
  id: 'id',
  taskType: 'taskType',
  title: 'title',
  description: 'description',
  xpReward: 'xpReward',
  itemRewardId: 'itemRewardId',
  bonusRewardAmount: 'bonusRewardAmount',
  bonusCurrencyId: 'bonusCurrencyId',
  targetValue: 'targetValue',
  durationDays: 'durationDays',
  isActive: 'isActive',
  requiredVipLevel: 'requiredVipLevel',
  resetCycle: 'resetCycle',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserVipTaskProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  taskId: 'taskId',
  progress: 'progress',
  isCompleted: 'isCompleted',
  rewardClaimedAt: 'rewardClaimedAt',
  lastProgressAt: 'lastProgressAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RebateTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  transactionId: 'transactionId',
  rebateAmount: 'rebateAmount',
  currencyId: 'currencyId',
  vipLevel: 'vipLevel',
  rebatePercentage: 'rebatePercentage',
  status: 'status',
  paidOutAt: 'paidOutAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  VIP: 'VIP',
  MODERATOR: 'MODERATOR',
  SYSTEM: 'SYSTEM',
  OWNER: 'OWNER',
  MEMBER: 'MEMBER',
  OPERATOR: 'OPERATOR',
  SUPPORT_AGENT: 'SUPPORT_AGENT'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  ACTIVE: 'ACTIVE',
  DEACTIVATED: 'DEACTIVATED',
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  SUSPENDED: 'SUSPENDED',
  BANNED: 'BANNED'
};

exports.Gender = exports.$Enums.Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  NON_BINARY: 'NON_BINARY',
  OTHER: 'OTHER',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY'
};

exports.KeyMode = exports.$Enums.KeyMode = {
  read: 'read',
  write: 'write',
  upload: 'upload',
  manage_users: 'manage_users',
  manage_settings: 'manage_settings',
  launch_game: 'launch_game'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  INSTORE_CASH: 'INSTORE_CASH',
  INSTORE_CARD: 'INSTORE_CARD',
  CASH_APP: 'CASH_APP'
};

exports.GameProvider = exports.$Enums.GameProvider = {
  PRAGMATICPLAY: 'PRAGMATICPLAY',
  EVOPLAY: 'EVOPLAY',
  NETENT: 'NETENT',
  PLAYNGO: 'PLAYNGO',
  RELAXGAMING: 'RELAXGAMING',
  HACKSAW: 'HACKSAW',
  BGAMING: 'BGAMING',
  SPRIBE: 'SPRIBE',
  INTERNAL: 'INTERNAL',
  REDTIGER: 'REDTIGER',
  NETGAME: 'NETGAME',
  BIGFISHGAMES: 'BIGFISHGAMES',
  CQNINE: 'CQNINE',
  NOLIMIT: 'NOLIMIT',
  KICKASS: 'KICKASS'
};

exports.GameCategory = exports.$Enums.GameCategory = {
  FISH: 'FISH',
  POKER: 'POKER',
  SLOTS: 'SLOTS',
  TABLE_GAMES: 'TABLE_GAMES',
  LIVE_CASINO: 'LIVE_CASINO',
  SPORTSBOOK: 'SPORTSBOOK',
  VIRTUAL_SPORTS: 'VIRTUAL_SPORTS',
  LOTTERY: 'LOTTERY',
  CRASH: 'CRASH',
  OTHER: 'OTHER'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  SYSTEM_MESSAGE: 'SYSTEM_MESSAGE',
  FRIEND_REQUEST_RECEIVED: 'FRIEND_REQUEST_RECEIVED',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  ACHIEVEMENT_UNLOCKED: 'ACHIEVEMENT_UNLOCKED',
  BALANCE_UPDATE: 'BALANCE_UPDATE',
  PROMOTIONAL_OFFER: 'PROMOTIONAL_OFFER',
  TOURNAMENT_INVITE: 'TOURNAMENT_INVITE',
  TOURNAMENT_RESULT: 'TOURNAMENT_RESULT',
  SECURITY_ALERT: 'SECURITY_ALERT',
  GAME_EVENT: 'GAME_EVENT',
  NEW_MESSAGE: 'NEW_MESSAGE',
  LEVEL_UP: 'LEVEL_UP',
  GENERAL_INFO: 'GENERAL_INFO',
  PROMOTION: 'PROMOTION',
  SECUITY_ALERT: 'SECUITY_ALERT',
  TRANSACTION_UPDATE: 'TRANSACTION_UPDATE',
  REWARD_UNLOCKED: 'REWARD_UNLOCKED',
  MAINTENANCE: 'MAINTENANCE'
};

exports.FriendshipStatus = exports.$Enums.FriendshipStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  BLOCKED: 'BLOCKED'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  BET: 'BET',
  WIN: 'WIN',
  TRANSFER_SENT: 'TRANSFER_SENT',
  TRANSFER_RECEIVED: 'TRANSFER_RECEIVED',
  SYSTEM_ADJUSTMENT_CREDIT: 'SYSTEM_ADJUSTMENT_CREDIT',
  SYSTEM_ADJUSTMENT_DEBIT: 'SYSTEM_ADJUSTMENT_DEBIT',
  TOURNAMENT_BUYIN: 'TOURNAMENT_BUYIN',
  TOURNAMENT_PRIZE: 'TOURNAMENT_PRIZE',
  AFFILIATE_COMMISSION: 'AFFILIATE_COMMISSION',
  REFUND: 'REFUND',
  FEE: 'FEE',
  BONUS_AWARD: 'BONUS_AWARD',
  BET_PLACE: 'BET_PLACE',
  BET_WIN: 'BET_WIN',
  BET_LOSE: 'BET_LOSE',
  BET_REFUND: 'BET_REFUND',
  BONUS_WAGER: 'BONUS_WAGER',
  BONUS_CONVERT: 'BONUS_CONVERT',
  BONUS_EXPIRED: 'BONUS_EXPIRED',
  XP_AWARD: 'XP_AWARD',
  ADJUSTMENT_ADD: 'ADJUSTMENT_ADD',
  ADJUSTMENT_SUB: 'ADJUSTMENT_SUB',
  INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
  PRODUCT_PURCHASE: 'PRODUCT_PURCHASE',
  REBATE_PAYOUT: 'REBATE_PAYOUT'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED',
  REQUIRES_ACTION: 'REQUIRES_ACTION',
  ON_HOLD: 'ON_HOLD'
};

exports.RewardType = exports.$Enums.RewardType = {
  DAILY_SIGN_IN: 'DAILY_SIGN_IN',
  WEEKLY_CYCLE: 'WEEKLY_CYCLE',
  MONTHLY_CYCLE: 'MONTHLY_CYCLE',
  LEVEL_UP: 'LEVEL_UP',
  VIP_TASK_COMPLETION: 'VIP_TASK_COMPLETION',
  BET_REBATE: 'BET_REBATE',
  ACHIEVEMENT_UNLOCKED: 'ACHIEVEMENT_UNLOCKED',
  PROMO_CODE: 'PROMO_CODE',
  DEPOSIT_BONUS: 'DEPOSIT_BONUS',
  REGISTRATION_BONUS: 'REGISTRATION_BONUS',
  FREE_SPINS: 'FREE_SPINS',
  TOURNAMENT_PRIZE: 'TOURNAMENT_PRIZE',
  OTHER: 'OTHER'
};

exports.RewardStatus = exports.$Enums.RewardStatus = {
  AVAILABLE: 'AVAILABLE',
  CLAIMED: 'CLAIMED',
  EXPIRED: 'EXPIRED',
  PENDING: 'PENDING',
  VOIDED: 'VOIDED'
};

exports.VipTaskType = exports.$Enums.VipTaskType = {
  DEPOSIT_STREAK: 'DEPOSIT_STREAK',
  WAGER_AMOUNT: 'WAGER_AMOUNT',
  LOGIN_STREAK: 'LOGIN_STREAK',
  PROFILE_COMPLETION: 'PROFILE_COMPLETION',
  PLAY_SPECIFIC_GAME: 'PLAY_SPECIFIC_GAME',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  PLACE_BETS: 'PLACE_BETS',
  WIN_STREAK: 'WIN_STREAK'
};

exports.Prisma.ModelName = {
  Currency: 'Currency',
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Profile: 'Profile',
  Settings: 'Settings',
  Wallet: 'Wallet',
  OperatorAccess: 'OperatorAccess',
  Achievement: 'Achievement',
  Game: 'Game',
  Post: 'Post',
  Comment: 'Comment',
  GameSpin: 'GameSpin',
  GameSession: 'GameSession',
  UserAchievement: 'UserAchievement',
  XpEvent: 'XpEvent',
  Notification: 'Notification',
  ChatMessage: 'ChatMessage',
  Friendship: 'Friendship',
  Transaction: 'Transaction',
  GameLaunchLink: 'GameLaunchLink',
  Product: 'Product',
  EventLog: 'EventLog',
  OperatorInvitation: 'OperatorInvitation',
  VipInfo: 'VipInfo',
  UserReward: 'UserReward',
  VipTask: 'VipTask',
  UserVipTaskProgress: 'UserVipTaskProgress',
  RebateTransaction: 'RebateTransaction'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
