/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdCarousel: typeof import('./../../components/home/AdCarousel.vue')['default']
    AllIcon: typeof import('./../../components/AnimatedIcons/AllIcon.vue')['default']
    AuroraText: typeof import('./../../components/common/AuroraText.vue')['default']
    BackGround: typeof import('./../../components/home/BackGround.vue')['default']
    Benefits: typeof import('./../../components/vip/components/benefits/index.vue')['default']
    ChatIcon: typeof import('./../../components/AnimatedIcons/ChatIcon.vue')['default']
    CircleProgressBar: typeof import('./../../components/layout/CircleProgressBar.vue')['default']
    CloseButton: typeof import('./../../components/common/CloseButton.vue')['default']
    DesktopSection: typeof import('./../../components/layout/DesktopSection.vue')['default']
    FilterBar: typeof import('./../../components/home/FilterBar.vue')['default']
    FishIcon: typeof import('./../../components/AnimatedIcons/FishIcon.vue')['default']
    FooterBar: typeof import('./../../components/layout/FooterBar.vue')['default']
    FooterBarMobile: typeof import('./../../components/layout/FooterBarMobile.vue')['default']
    FormCheckRadio: typeof import('./../../components/common/FormCheckRadio.vue')['default']
    FormCheckRadioGroup: typeof import('./../../components/common/FormCheckRadioGroup.vue')['default']
    GameCarousel: typeof import('./../../components/home/GameCarousel.vue')['default']
    GlassButton: typeof import('./../../components/common/GlassButton.vue')['default']
    GlobalLoading: typeof import('./../../components/common/GlobalLoading.vue')['default']
    Index1: typeof import('./../../components/vip/mobile/index1.vue')['default']
    LayoutAuthenticated: typeof import('./../../components/layout/LayoutAuthenticated.vue')['default']
    LiveWin: typeof import('./../../components/home/LiveWin.vue')['default']
    Loading: typeof import('./../../components/common/Loading.vue')['default']
    Logo: typeof import('./../../components/common/Logo.vue')['default']
    MBonusDashboard: typeof import('./../../components/vip/mobile/MBonusDashboard.vue')['default']
    Mobile: typeof import('./../../components/vip/mobile/index.vue')['default']
    MobileSection: typeof import('./../../components/layout/MobileSection.vue')['default']
    OverlayLayer: typeof import('./../../components/common/OverlayLayer.vue')['default']
    PlayerAvatar: typeof import('./../../components/layout/PlayerAvatar.vue')['default']
    Progress: typeof import('./../../components/vip/components/progress/index.vue')['default']
    RaceAnnouncement: typeof import('./../../components/races/RaceAnnouncement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectPayment: typeof import('./../../components/shop/SelectPayment.vue')['default']
    SelectProduct: typeof import('./../../components/shop/SelectProduct.vue')['default']
    SettingsView: typeof import('./../../components/home/SettingsView.vue')['default']
    ShopConfirm: typeof import('./../../components/shop/ShopConfirm.vue')['default']
    ShopView: typeof import('./../../components/shop/ShopView.vue')['default']
    ShowToasts: typeof import('./../../components/common/ShowToasts.vue')['default']
    SlotsIcon: typeof import('./../../components/AnimatedIcons/SlotsIcon.vue')['default']
    SparklesSprite: typeof import('./../../components/layout/SparklesSprite.vue')['default']
    SpriteAnimation: typeof import('./../../components/common/SpriteAnimation.vue')['default']
    StoreId: typeof import('./../../components/shop/StoreId.vue')['default']
    TopBar: typeof import('./../../components/layout/TopBar.vue')['default']
    TopBarMobile: typeof import('./../../components/layout/TopBarMobile.vue')['default']
    UserBlock: typeof import('./../../components/layout/UserBlock.vue')['default']
    VGSprite: typeof import('./../../components/common/VGSprite.vue')['default']
    Vip_bonus: typeof import('./../../components/vip/components/vip_bonus/index.vue')['default']
    Vip_upgrade_dialog: typeof import('./../../components/vip/components/vip_upgrade_dialog/index.vue')['default']
    Vip_uprank_dialog: typeof import('./../../components/vip/components/vip_uprank_dialog/index.vue')['default']
    VSprite: typeof import('./../../components/common/VSprite.vue')['default']
    WheelIcon: typeof import('./../../components/AnimatedIcons/WheelIcon.vue')['default']
    XPStars: typeof import('./../../components/AnimatedIcons/XPStars.vue')['default']
  }
}
